GET http://localhost:5147/api/users
Authorization: mysecrettoken
###
GET http://localhost:5147/api/users/1
Authorization: mysecrettoken
###
GET http://localhost:5147/api/users/4
Authorization: mysecrettoken

###
POST http://localhost:5147/api/users
Authorization: mysecrettoken
Content-Type: application/json

{
    "id": 3,
    "name":"sara",
    "email":"sara@gmail.com"
}
###
PUT http://localhost:5147/api/users/3
Authorization: mysecrettoken
Content-Type: application/json

{
    "id": 4,
    "name":"doa",
    "email":"doaa@gmail.com"
}
###
DELETE http://localhost:5147/api/users/3
Authorization: mysecrettoken
